AUTHORS_TO_EXCLUDE = [
  'aws-cdk-automation',
  'rix0rrr',
  'iliapolo',
  'otaviomacedo',
  'kaizencc',
  'TheRealAmazonKendra',
  'mrgrain',
  'pahud',
  'ashishdhingra',
  'kellertk',
  'moelasmar',
  'paulhcsun',
  'GavinZZ',
  'xazhao',
  'gracelu0',
  'shikha372',
  'QuantumNeuralCoder',
  'godwingrs22',
  'bergjaak',
  'samson-keung',
  'IanKonlog',
  'Leo10Gama',
  'scorbiere',
  'jiayiwang7',
  'saiyush',
  '5d',
  'iankhou',
  'SimonCMoore',
  'github-advanced-security',
  'dependabot',
  'github-actions'
]

EXCLUDED_LABELS = ['contribution/core']